// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/log"
)

type MemoryMonitor struct {
	LogMemoryUsageStub        func(string)
	logMemoryUsageMutex       sync.RWMutex
	logMemoryUsageArgsForCall []struct {
		arg1 string
	}
	LogMemoryUsageOnEndStub        func()
	logMemoryUsageOnEndMutex       sync.RWMutex
	logMemoryUsageOnEndArgsForCall []struct {
	}
	LogMemoryUsageOnStartStub        func()
	logMemoryUsageOnStartMutex       sync.RWMutex
	logMemoryUsageOnStartArgsForCall []struct {
	}
	LogMemoryUsagefStub        func(string, ...interface{})
	logMemoryUsagefMutex       sync.RWMutex
	logMemoryUsagefArgsForCall []struct {
		arg1 string
		arg2 []interface{}
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *MemoryMonitor) LogMemoryUsage(arg1 string) {
	fake.logMemoryUsageMutex.Lock()
	fake.logMemoryUsageArgsForCall = append(fake.logMemoryUsageArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.LogMemoryUsageStub
	fake.recordInvocation("LogMemoryUsage", []interface{}{arg1})
	fake.logMemoryUsageMutex.Unlock()
	if stub != nil {
		fake.LogMemoryUsageStub(arg1)
	}
}

func (fake *MemoryMonitor) LogMemoryUsageCallCount() int {
	fake.logMemoryUsageMutex.RLock()
	defer fake.logMemoryUsageMutex.RUnlock()
	return len(fake.logMemoryUsageArgsForCall)
}

func (fake *MemoryMonitor) LogMemoryUsageCalls(stub func(string)) {
	fake.logMemoryUsageMutex.Lock()
	defer fake.logMemoryUsageMutex.Unlock()
	fake.LogMemoryUsageStub = stub
}

func (fake *MemoryMonitor) LogMemoryUsageArgsForCall(i int) string {
	fake.logMemoryUsageMutex.RLock()
	defer fake.logMemoryUsageMutex.RUnlock()
	argsForCall := fake.logMemoryUsageArgsForCall[i]
	return argsForCall.arg1
}

func (fake *MemoryMonitor) LogMemoryUsageOnEnd() {
	fake.logMemoryUsageOnEndMutex.Lock()
	fake.logMemoryUsageOnEndArgsForCall = append(fake.logMemoryUsageOnEndArgsForCall, struct {
	}{})
	stub := fake.LogMemoryUsageOnEndStub
	fake.recordInvocation("LogMemoryUsageOnEnd", []interface{}{})
	fake.logMemoryUsageOnEndMutex.Unlock()
	if stub != nil {
		fake.LogMemoryUsageOnEndStub()
	}
}

func (fake *MemoryMonitor) LogMemoryUsageOnEndCallCount() int {
	fake.logMemoryUsageOnEndMutex.RLock()
	defer fake.logMemoryUsageOnEndMutex.RUnlock()
	return len(fake.logMemoryUsageOnEndArgsForCall)
}

func (fake *MemoryMonitor) LogMemoryUsageOnEndCalls(stub func()) {
	fake.logMemoryUsageOnEndMutex.Lock()
	defer fake.logMemoryUsageOnEndMutex.Unlock()
	fake.LogMemoryUsageOnEndStub = stub
}

func (fake *MemoryMonitor) LogMemoryUsageOnStart() {
	fake.logMemoryUsageOnStartMutex.Lock()
	fake.logMemoryUsageOnStartArgsForCall = append(fake.logMemoryUsageOnStartArgsForCall, struct {
	}{})
	stub := fake.LogMemoryUsageOnStartStub
	fake.recordInvocation("LogMemoryUsageOnStart", []interface{}{})
	fake.logMemoryUsageOnStartMutex.Unlock()
	if stub != nil {
		fake.LogMemoryUsageOnStartStub()
	}
}

func (fake *MemoryMonitor) LogMemoryUsageOnStartCallCount() int {
	fake.logMemoryUsageOnStartMutex.RLock()
	defer fake.logMemoryUsageOnStartMutex.RUnlock()
	return len(fake.logMemoryUsageOnStartArgsForCall)
}

func (fake *MemoryMonitor) LogMemoryUsageOnStartCalls(stub func()) {
	fake.logMemoryUsageOnStartMutex.Lock()
	defer fake.logMemoryUsageOnStartMutex.Unlock()
	fake.LogMemoryUsageOnStartStub = stub
}

func (fake *MemoryMonitor) LogMemoryUsagef(arg1 string, arg2 ...interface{}) {
	fake.logMemoryUsagefMutex.Lock()
	fake.logMemoryUsagefArgsForCall = append(fake.logMemoryUsagefArgsForCall, struct {
		arg1 string
		arg2 []interface{}
	}{arg1, arg2})
	stub := fake.LogMemoryUsagefStub
	fake.recordInvocation("LogMemoryUsagef", []interface{}{arg1, arg2})
	fake.logMemoryUsagefMutex.Unlock()
	if stub != nil {
		fake.LogMemoryUsagefStub(arg1, arg2...)
	}
}

func (fake *MemoryMonitor) LogMemoryUsagefCallCount() int {
	fake.logMemoryUsagefMutex.RLock()
	defer fake.logMemoryUsagefMutex.RUnlock()
	return len(fake.logMemoryUsagefArgsForCall)
}

func (fake *MemoryMonitor) LogMemoryUsagefCalls(stub func(string, ...interface{})) {
	fake.logMemoryUsagefMutex.Lock()
	defer fake.logMemoryUsagefMutex.Unlock()
	fake.LogMemoryUsagefStub = stub
}

func (fake *MemoryMonitor) LogMemoryUsagefArgsForCall(i int) (string, []interface{}) {
	fake.logMemoryUsagefMutex.RLock()
	defer fake.logMemoryUsagefMutex.RUnlock()
	argsForCall := fake.logMemoryUsagefArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *MemoryMonitor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *MemoryMonitor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ log.MemoryMonitor = new(MemoryMonitor)
